#!/data/data/com.termux/files/usr/bin/bash
# Handles TEL's status window
# v0.1 03/04/2020
# made by @SealyJ


# import tel stuff
source ~/.tel/config/status
source ~/.tel/dev/helpers.sh #need wraptext function
source ~/.tel/dev/colors.sh #currently unused
 
# run the welcome / startup animation script
~/.tel/status/welcome

# does user want status pane?
[[ "$STATUS_ENABLED" == "false" ]] && exit 0


notif_path=~/.tel/usr/.notifs

status_rows=$(("$(ls ~/.tel/status_scripts/active | wc -w)" + 1))

if [ $NOTIFICATIONS == true ] ; then
	oldnotifs=""
	python ~/.tel/status/get_notifications & # start notification listener as child
fi

while [ 1 ]
do
	tmux resizep -t 0 -y $status_rows
#	status=$(timeout $STATUS_RELOAD $HOME/.tel/status/get_status_info)
#	printf "\033c" #clear screen
	if [ "$NOTIFICATIONS" == true ] ; then
		notifs=$(cat $notif_path)
       		if [ "$notifs" != "$oldnotifs" ] ; then
			rows="$(tput lines)"
			#notif lines text shpuld be wrapped first for proper resize and delay
			notif_lines="$(wc -l $notif_path | cut -d' ' -f1)"
			status_rows=$(("$(ls ~/.tel/status_scripts/active | wc -w)" + 1))
			if [ "$notif_lines" -gt "$rows" ]; then
				tmux resizep -t 0 -y $notif_lines
			fi
			printf "\033c" #clear screen
			center_text "Notifications:"
			echo "${notifs}"
	        	oldnotifs=$notifs
			sleep $notif_lines
			sleep 1
		else
                	status=$(timeout $STATUS_RELOAD $HOME/.tel/status/get_status_info)
	                printf "\033c" #clear screen
			echo "${status}"
			tmux clearhist -t 0
			sleep $STATUS_RELOAD
		fi
	else
                status=$(timeout $STATUS_RELOAD $HOME/.tel/status/get_status_info)
		printf "\033c" #clear screen
		echo "${status}"
		tmux clearhist -t 0
		sleep $STATUS_RELOAD
	fi
	done
