version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  cooldown:
    default-days: 7
  commit-message:
    # Prefix all commit messages with "Changed: "
    prefix: "Changed"
