#!/data/data/com.termux/files/usr/bin/sh
ps -ef | grep 'termux.x11*' | grep -v grep | awk '{print $2}'| xargs -r kill -9
ps -ef | grep 'termux.x11*' | grep -v grep | awk '{print $2}'| xargs -r kill -9
