name: "Bug report"
description: "Create a report to help us improve"
title: "[Bug]: "
labels: ["bug report"]
body:
  - type: markdown
    attributes:
      value: |
        **THIS IS A BUG TRACKER OF THE TERMUX APP. IF YOU HAVE ISSUES WITH A PACKAGE INSIDE THE APP, THEN PLEASE OPEN AN ISSUE AT [TERMUX/TERMUX-PACKAGES](https://github.com/termux/termux-packages) INSTEAD.**
        If you are unsure if this is a bug with the Termux app itself or any of the packages, kindly open up the bug at [termux/termux-packages](https://github.com/termux/termux-packages) as it's very likely that it belongs there.

        Use search before you open an issue to check whether your issue has been already reported and perhaps solved.

        Android versions 5.x and 6.x are not supported anymore.

        If you have issues installing packages then please see https://github.com/termux/termux-packages/issues/6726.
  - type: textarea
    attributes:
      label: Problem description
      description: |
        A clear and concise description of what the problem is. You may attach the logs, screenshots, screen video recording and whatever else that will help to understand the issue.

        Issues without proper description will be closed without solution.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the behavior.
      description: |
        Please post all necessary commands that are needed to reproduce the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
  - type: textarea
    attributes:
      label: System information
      description: Please provide info about your device
      value: |
        * Termux application version:
        * Android OS version:
        * Device model:
    validations:
      required: true
