.\" Copyright \(co 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1994, 1996 X Consortium
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining
.\" a copy of this software and associated documentation files (the
.\" "Software"), to deal in the Software without restriction, including
.\" without limitation the rights to use, copy, modify, merge, publish,
.\" distribute, sublicense, and/or sell copies of the Software, and to
.\" permit persons to whom the Software is furnished to do so, subject to
.\" the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included
.\" in all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
.\" OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE X CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR
.\" OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
.\" ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
.\" OTHER DEALINGS IN THE SOFTWARE.
.\"
.\" Except as contained in this notice, the name of the X Consortium shall
.\" not be used in advertising or otherwise to promote the sale, use or
.\" other dealings in this Software without prior written authorization
.\" from the X Consortium.
.\"
.\" Copyright \(co 1985, 1986, 1987, 1988, 1989, 1990, 1991 by
.\" Digital Equipment Corporation
.\"
.\" Portions Copyright \(co 1990, 1991 by
.\" Tektronix, Inc.
.\"
.\" Permission to use, copy, modify and distribute this documentation for
.\" any purpose and without fee is hereby granted, provided that the above
.\" copyright notice appears in all copies and that both that copyright notice
.\" and this permission notice appear in all copies, and that the names of
.\" Digital and Tektronix not be used in in advertising or publicity pertaining
.\" to this documentation without specific, written prior permission.
.\" Digital and Tektronix makes no representations about the suitability
.\" of this documentation for any purpose.
.\" It is provided "as is" without express or implied warranty.
.\"
.\"
.ds xT X Toolkit Intrinsics \- C Language Interface
.ds xW Athena X Widgets \- C Language X Toolkit Interface
.ds xL Xlib \- C Language X Interface
.ds xC Inter-Client Communication Conventions Manual
.TH XcmsTekHVCQueryMaxC __libmansuffix__ __xorgversion__ "XLIB FUNCTIONS"
.SH NAME
XcmsTekHVCQueryMaxC, XcmsTekHVCQueryMaxV, XcmsTekHVCQueryMaxVC, XcmsTekHVCQueryMaxVSamples, XcmsTekHVCQueryMinV \- obtain the TekHVC coordinates
.SH SYNTAX
.HP
Status XcmsTekHVCQueryMaxC\^(\^XcmsCCC \fIccc\fP\^, XcmsFloat \fIhue\fP\^,
XcmsFloat \fIvalue\fP\^, XcmsColor *\fIcolor_return\fP\^);
.HP
Status XcmsTekHVCQueryMaxV\^(\^XcmsCCC \fIccc\fP\^, XcmsFloat \fIhue\fP\^,
XcmsFloat \fIchroma\fP\^, XcmsColor *\fIcolor_return\fP\^);
.HP
Status XcmsTekHVCQueryMaxVC\^(\^XcmsCCC \fIccc\fP\^, XcmsFloat \fIhue\fP\^,
XcmsColor *\fIcolor_return\fP\^);
.HP
Status XcmsTekHVCQueryMaxVSamples\^(\^XcmsCCC \fIccc\fP\^, XcmsFloat
\fIhue\fP\^, XcmsColor \fIcolors_return[]\fP\^, unsigned int
\fInsamples\fP\^);
.HP
Status XcmsTekHVCQueryMinV\^(\^XcmsCCC \fIccc\fP\^, XcmsFloat \fIhue\fP\^,
XcmsFloat \fIchroma\fP\^, XcmsColor *\fIcolor_return\fP\^);
.SH ARGUMENTS
.IP \fIccc\fP 1i
Specifies the CCC.
Note that the CCC's Client White Point and White Point Adjustment procedures
are ignored.
.IP \fIchroma\fP 1i
Specifies the chroma at which to find maximum Value (MaxV).
.IP \fIcolors_return\fP 1i
Returns nsamples of color specifications in XcmsTekHVC
such that the Chroma is the maximum attainable for the Value and Hue.
The white point associated with the returned
color specification is the Screen White Point.
The value returned in the pixel member is undefined.
.ds Lc
.ds lC
.IP \fIcolor_return\fP 1i
Returns the maximum Chroma along with the actual Hue and Value (MaxC),
maximum Value along with the Hue and Chroma (MaxV),
color specification in XcmsTekHVC for the maximum Chroma,
the Value at which that maximum Chroma is reached and actual Hue (MaxVC)
or minimum Value and the actual Hue and Chroma (MinL)
at which the maximum Chroma (MaxC and MaxVC), maximum Value (MaxV), or
minimum Value (MinL) was found.
The white point associated with the returned
color specification is the Screen White Point.
The value returned in the pixel member is undefined.
.IP \fIhue\fP 1i
Specifies the Hue in which to find the maximum Chroma (MaxC and MaxVC),
maximum Value (MaxV), the maximum Chroma/Value samples (MaxVSamples),
or the minimum Value (MinL).
.IP \fInsamples\fP 1i
Specifies the number of samples.
.IP \fIvalue\fP 1i
Specifies the Value in which to find the maximum Chroma (MaxC) or minimum Value (MinL).
.SH DESCRIPTION
The
.B XcmsTekHVCQueryMaxC
function, given a Hue and Value,
determines the maximum Chroma in TekHVC color space
displayable by the screen.
It returns the maximum Chroma along with the actual Hue
and Value at which the maximum Chroma was found.
.LP
The
.B XcmsTekHVCQueryMaxV
function, given a Hue and Chroma,
determines the maximum Value in TekHVC color space
displayable by the screen.
It returns the maximum Value and the actual Hue and Chroma
at which the maximum Value was found.
.LP
The
.B XcmsTekHVCQueryMaxVC
function, given a Hue,
determines the maximum Chroma in TekHVC color space displayable by the screen
and the Value at which that maximum Chroma is reached.
It returns the maximum Chroma,
the Value at which that maximum Chroma is reached,
and the actual Hue for which the maximum Chroma was found.
.LP
The
.B XcmsTekHVCQueryMaxVSamples
returns nsamples of maximum Value, the Chroma at which that maximum Value
is reached, and the actual Hue for which the maximum Chroma was found.
These sample points may then be used to plot the maximum Value/Chroma
boundary of the screen's color gamut for the specified Hue in TekHVC color
space.
.LP
The
.B XcmsTekHVCQueryMinV
function, given a Hue and Chroma,
determines the minimum Value in TekHVC color space displayable by the screen.
It returns the minimum Value and the actual Hue and Chroma at which
the minimum Value was found.
.SH "SEE ALSO"
XcmsCIELabQueryMaxC(__libmansuffix__),
XcmsCIELuvQueryMaxC(__libmansuffix__),
XcmsQueryBlack(__libmansuffix__)
.br
\fI\*(xL\fP
