.\" Copyright \(co 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1994, 1996 X Consortium
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining
.\" a copy of this software and associated documentation files (the
.\" "Software"), to deal in the Software without restriction, including
.\" without limitation the rights to use, copy, modify, merge, publish,
.\" distribute, sublicense, and/or sell copies of the Software, and to
.\" permit persons to whom the Software is furnished to do so, subject to
.\" the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included
.\" in all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
.\" OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE X CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR
.\" OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
.\" ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
.\" OTHER DEALINGS IN THE SOFTWARE.
.\"
.\" Except as contained in this notice, the name of the X Consortium shall
.\" not be used in advertising or otherwise to promote the sale, use or
.\" other dealings in this Software without prior written authorization
.\" from the X Consortium.
.\"
.\" Copyright \(co 1985, 1986, 1987, 1988, 1989, 1990, 1991 by
.\" Digital Equipment Corporation
.\"
.\" Portions Copyright \(co 1990, 1991 by
.\" Tektronix, Inc.
.\"
.\" Permission to use, copy, modify and distribute this documentation for
.\" any purpose and without fee is hereby granted, provided that the above
.\" copyright notice appears in all copies and that both that copyright notice
.\" and this permission notice appear in all copies, and that the names of
.\" Digital and Tektronix not be used in in advertising or publicity pertaining
.\" to this documentation without specific, written prior permission.
.\" Digital and Tektronix makes no representations about the suitability
.\" of this documentation for any purpose.
.\" It is provided "as is" without express or implied warranty.
.\"
.\"
.ds xT X Toolkit Intrinsics \- C Language Interface
.ds xW Athena X Widgets \- C Language X Toolkit Interface
.ds xL Xlib \- C Language X Interface
.ds xC Inter-Client Communication Conventions Manual
.TH XInstallColormap __libmansuffix__ __xorgversion__ "XLIB FUNCTIONS"
.SH NAME
XInstallColormap, XUninstallColormap, XListInstalledColormaps \- control colormaps
.SH SYNTAX
.HP
int XInstallColormap\^(\^Display *\fIdisplay\fP\^, Colormap \fIcolormap\fP\^);
.HP
int XUninstallColormap\^(\^Display *\fIdisplay\fP\^, Colormap
\fIcolormap\fP\^);
.HP
Colormap *XListInstalledColormaps\^(\^Display *\fIdisplay\fP\^, Window
\fIw\fP\^, int *\fInum_return\fP\^);
.SH ARGUMENTS
.IP \fIcolormap\fP 1i
Specifies the colormap.
.IP \fIdisplay\fP 1i
Specifies the connection to the X server.
.IP \fInum_return\fP 1i
Returns the number of currently installed colormaps.
.IP \fIw\fP 1i
Specifies the window that determines the screen.
.SH DESCRIPTION
The
.B XInstallColormap
function installs the specified colormap for its associated screen.
All windows associated with this colormap immediately display with
true colors.
You associated the windows with this colormap when you created them by calling
.BR XCreateWindow ,
.BR XCreateSimpleWindow ,
.BR XChangeWindowAttributes ,
or
.BR XSetWindowColormap .
.LP
If the specified colormap is not already an installed colormap,
the X server generates a
.B ColormapNotify
event on each window that has that colormap.
In addition, for every other colormap that is installed as
a result of a call to
.BR XInstallColormap ,
the X server generates a
.B ColormapNotify
event on each window that has that colormap.
.LP
.B XInstallColormap
can generate a
.B BadColor
error.
.LP
The
.B XUninstallColormap
function removes the specified colormap from the required
list for its screen.
As a result,
the specified colormap might be uninstalled,
and the X server might implicitly install or uninstall additional colormaps.
Which colormaps get installed or uninstalled is server dependent
except that the required list must remain installed.
.LP
If the specified colormap becomes uninstalled,
the X server generates a
.B ColormapNotify
event on each window that has that colormap.
In addition, for every other colormap that is installed or uninstalled as a
result of a call to
.BR XUninstallColormap ,
the X server generates a
.B ColormapNotify
event on each window that has that colormap.
.LP
.B XUninstallColormap
can generate a
.B BadColor
error.
.LP
The
.B XListInstalledColormaps
function returns a list of the currently installed colormaps for the screen
of the specified window.
The order of the colormaps in the list is not significant
and is no explicit indication of the required list.
When the allocated list is no longer needed,
free it by using
.BR XFree .
.LP
.B XListInstalledColormaps
can generate a
.B BadWindow
error.
.SH DIAGNOSTICS
.TP 1i
.B BadColor
A value for a Colormap argument does not name a defined Colormap.
.TP 1i
.B BadWindow
A value for a Window argument does not name a defined Window.
.SH "SEE ALSO"
XChangeWindowAttributes(__libmansuffix__),
XCreateColormap(__libmansuffix__),
XCreateWindow(__libmansuffix__),
XFree(__libmansuffix__)
.br
\fI\*(xL\fP
