.\" Copyright \(co 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1994, 1996 X Consortium
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining
.\" a copy of this software and associated documentation files (the
.\" "Software"), to deal in the Software without restriction, including
.\" without limitation the rights to use, copy, modify, merge, publish,
.\" distribute, sublicense, and/or sell copies of the Software, and to
.\" permit persons to whom the Software is furnished to do so, subject to
.\" the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included
.\" in all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
.\" OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE X CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR
.\" OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
.\" ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
.\" OTHER DEALINGS IN THE SOFTWARE.
.\"
.\" Except as contained in this notice, the name of the X Consortium shall
.\" not be used in advertising or otherwise to promote the sale, use or
.\" other dealings in this Software without prior written authorization
.\" from the X Consortium.
.\"
.\" Copyright \(co 1985, 1986, 1987, 1988, 1989, 1990, 1991 by
.\" Digital Equipment Corporation
.\"
.\" Portions Copyright \(co 1990, 1991 by
.\" Tektronix, Inc.
.\"
.\" Permission to use, copy, modify and distribute this documentation for
.\" any purpose and without fee is hereby granted, provided that the above
.\" copyright notice appears in all copies and that both that copyright notice
.\" and this permission notice appear in all copies, and that the names of
.\" Digital and Tektronix not be used in in advertising or publicity pertaining
.\" to this documentation without specific, written prior permission.
.\" Digital and Tektronix makes no representations about the suitability
.\" of this documentation for any purpose.
.\" It is provided "as is" without express or implied warranty.
.\"
.\"
.ds xT X Toolkit Intrinsics \- C Language Interface
.ds xW Athena X Widgets \- C Language X Toolkit Interface
.ds xL Xlib \- C Language X Interface
.ds xC Inter-Client Communication Conventions Manual
.TH XQueryTree __libmansuffix__ __xorgversion__ "XLIB FUNCTIONS"
.SH NAME
XQueryTree \- query window tree information
.SH SYNTAX
.HP
Status XQueryTree\^(\^Display *\fIdisplay\fP\^, Window \fIw\fP\^, Window
*\fIroot_return\fP\^, Window *\fIparent_return\fP\^, Window
**\fIchildren_return\fP\^, unsigned int *\fInchildren_return\fP\^);
.SH ARGUMENTS
.IP \fIchildren_return\fP 1i
Returns the list of children.
.IP \fIdisplay\fP 1i
Specifies the connection to the X server.
.IP \fInchildren_return\fP 1i
Returns the number of children.
.IP \fIparent_return\fP 1i
Returns the parent window.
.IP \fIroot_return\fP 1i
Returns the root window.
.IP \fIw\fP 1i
Specifies the window whose list of children, root, parent, and number of children
you want to obtain.
.SH DESCRIPTION
The
.B XQueryTree
function returns the root ID, the parent window ID,
a pointer to the list of children windows
(NULL when there are no children),
and the number of children in the list for the specified window.
The children are listed in current stacking order, from bottom-most
(first) to top-most (last).
.B XQueryTree
returns zero if it fails and nonzero if it succeeds.
To free a non-NULL children list when it is no longer needed, use
.BR XFree .
.LP
.B XQueryTree
can generate a
.B BadWindow
error.
.SH BUGS
This really should return a screen *, not a root window ID.
.SH DIAGNOSTICS
.TP 1i
.B BadWindow
A value for a Window argument does not name a defined Window.
.SH "SEE ALSO"
XFree(__libmansuffix__),
XGetWindowAttributes(__libmansuffix__),
XQueryPointer(__libmansuffix__)
.br
\fI\*(xL\fP
