#!/data/data/com.termux/files/usr/bin/bash
source ~/.tel/helpers.sh 
logo="$(echo '
              * *    
           *    *  *
      *  *    *     *  *
   . *     *    *  *    *
 *     *    *    *    *   *
 *     *  *  #   * .#  *    
 *   *.       #  "#  *   *       
  *     "#.  #: #" *     .
    " * *."#. ##"    , .
           "###            Termux
             "##           Environment
              ##.          Launcher
              .##:
              :###
              ;###
            ,####,
      ____.######".____
     /  .#" "#   ".." .\
    / " "   .#    .  "  \
   /_____________________\
   \        [TEL]        /
    \___________________/


    ')"
center_text logo
