default: all

top_srcdir = .
include $(top_srcdir)/Makefile.win32.common

all: pixman test

pixman:
	@$(MAKE) -C pixman -f Makefile.win32

test:
	@$(MAKE) -C test -f Makefile.win32

clean_r:
	@$(MAKE) -C pixman -f Makefile.win32 clean
	@$(MAKE) -C test   -f Makefile.win32 clean

check:
	@$(MAKE) -C test -f Makefile.win32 check


clean: clean_r


.PHONY: all pixman test clean check
