#!/bin/sh

case $# in
    1)
	me="$1"
	;;
    *)
	echo 'Usage: $0 <my-name>'
	exit 1
	;;
esac

for i in `cat duplicate-files`; do
    if [ -f $i ]; then
	mkdir -p $me/`dirname $i`
	echo git mv $i $me/$i
	git mv $i $me/$i
    fi
done

git commit -m"Move common $me files out of the way"
