#!/usr/bin/env bash
# Used to insert a hint into motd for restart of tel app
# Enabled / disabled in .tel/configs/userprefs.sh

hints=("Use 'app your_app_name' to launch an app." "'todo' displays a list of your notes, use 'todo -h' to find out more" "Running 'termux-setup-storage' will allow a proper backup of your tel data" "look at the file \~\/.aliases to learn where to add your own" "use 'p your_contacts_name' to start a phone call, requires api to show contacts" "checkout the TEL community on Telegram\!" "Use 'tel-help' or 'tel-tutorial' to find out more" "use tel-search with bangs: 's \!!w dna'  \= search wikipedia for dna" "the alias 'weather' prints a forecast based on location set in configs" "checkout the config files in ~\/.tel\/configs\/" "'tel-notifications' pretty prints ypur current android notifications to the terminal" "Use tab key to autocomplete commands!" "both the app launcher and dialer can be used without supplying any arguments \/ data" "with the styling app installed you can longpress screen and select 'more' \> 'style' to easily change colorscheme and font" "Use 'tel-backup' to take a compressed copy of your home directory" "Search the youtube app with 'tel-search -yt yoursearchterm'" "'CTRL \+ n' Opens a new window" "'ALT \+ f' toggles the current pane to fullscreen" "'tel-edit' searches from it\'s current directory down" "'tel-open' searches for and opens files in external apps" "Most tel commands support the '-h' option to display user help e.g 'tel-dialer -h'" "status bar icon colors give you feedback at a glance, e.g. red storage icon = less than 10\% free diskspace" "'ALT \+ a' opens the app launcher in a new window" "'ALT \+ p' opens tel-dialer in a new window" "'ALT \+ s' opens tel-search in a new window" "'ALT \+ e' opens tel-edit in a new window" "'ALT \+ o' opens tel-open in a new window" "'CTRL \+ z' toggles the running program between foreground and background")

picker=$(echo $((0 + RANDOM % ${#hints[@]}))) #choose random index
hint="Hint: $(echo ${hints[$picker]})" #compose string
sed -i "8s/.*/${hint}/" ~/../usr/etc/motd #replace previous hint in motd

